services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres-tasks
  #   env_file:
  #     - .env.production

  # app-dev-tasks:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres-tasks
  #   env_file:
  #     - .env.development
  
  postgres-tasks:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dbtasks
    volumes:
      - postgres_tasks_data:/var/lib/postgresql/data

volumes:
  postgres_tasks_data: